const SECOND_MS = 1000;
const MINUTE_MS = 60 * SECOND_MS;

export const CODEX = {
	auth: {
		issuer: "https://auth.openai.com",
		clientId: "app_EMoamEEZ73f0CkXaXp7hrann",
		userCodePath: "/api/accounts/deviceauth/usercode",
		pollPath: "/api/accounts/deviceauth/token",
		tokenPath: "/oauth/token",
		revokePath: "/oauth/revoke",
		verificationPath: "/codex/device",
		callbackPath: "/deviceauth/callback",
		deviceLifetimeMs: 15 * MINUTE_MS,
		minIntervalSeconds: 3,
		defaultIntervalSeconds: 5,
		requestTimeoutMs: 15 * SECOND_MS,
		refreshTimeoutMs: 20 * SECOND_MS,
		refreshSkewMs: 2 * MINUTE_MS,
		lockTimeoutMs: 45 * SECOND_MS,
		reconnectErrors: [
			"invalid_grant",
			"refresh_token_reused",
			"refresh_token_expired",
			"refresh_token_invalidated",
		],
	},
	backend: {
		baseURL: "https://chatgpt.com/backend-api/codex",
		responsesPath: "/responses",
		modelsPath: "/models",
		clientVersion: "99.0.0",
		originator: "crm-startos",
		userAgent: "crm-startos",
		defaultInstructions: "You are a helpful assistant.",
		requestKeys: [
			"model",
			"stream",
			"service_tier",
			"instructions",
			"input",
			"tools",
			"tool_choice",
			"parallel_tool_calls",
			"reasoning",
			"store",
			"include",
			"prompt_cache_key",
			"text",
		],
		modelListTimeoutMs: 10 * SECOND_MS,
		maxResponseBytes: 1024 * 1024,
	},
	platform: {
		baseURL: "https://api.openai.com/v1",
		responsesPath: "/responses",
		modelsPath: "/models",
		modelListTimeoutMs: 10 * SECOND_MS,
	},
	sealing: {
		version: "v1",
		keyBytes: 32,
		ivBytes: 12,
	},
} as const;
